apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-chatbot
    component: backend
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: todo-chatbot
    component: backend
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
