apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-chatbot
    component: frontend
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: todo-chatbot
    component: frontend
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
