apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-chatbot
    component: mcp
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: todo-chatbot
    component: mcp
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
